### ISSUE TITLE
MiDeFace in 7.3.2 does not seem to work

### ISSUE THREAD

**Issue by klemens-egger** [freesurfer/freesurfer#1042]
I am trying to use the Freesurfer script MiDeFace to anonymize my anatomical data. 

I am using docker to have the Freesurfer v7.3.2. containerised. 

This is the code to run the container
`docker run -it --rm -v <path_to_BIDS_dataset>:/data freesurfer/freesurfer:7.3.2`

when trying to run this code:
`mideface --i /data/sub-01/ses-01/anat/sub-01_ses-01_T1w.nii --o /data/sub-01/ses-01/anat/sub-01_ses-01_T1w.defaced.nii --odir /data/sub-01/ses-01/anat --no-samseg-fast --nii`

I get the following output, and I did not find any solution online. 

####
Tue Dec 20 16:00:41 UTC 2022

setenv SUBJECTS_DIR /data
cd /root
/usr/local/freesurfer/bin/mideface --i /data/sub-01/ses-01/anat/sub-01_ses-01_T1w.nii --o /data/sub-01/ses-01/anat/sub-01_ses-01_T1w.defaced.nii
-rwxrwxr-x. 1 root root 27366 Aug  4 04:51 /usr/local/freesurfer/bin/mideface

freesurfer-linux-centos8_x86_64-7.3.2-20220804-6354275
$Id$
Linux 86a9c252ea7d 4.18.0-408.el8.x86_64 #1 SMP Mon Jul 18 17:42:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
pid 377
UseXvfb 0
samseg --i /data/sub-01/ses-01/anat/sub-01_ses-01_T1w.nii --o /data/sub-01/ses-01/anat/tmpdir.midefacer.377/samseg --threads 1 --block-coordinate-descent --options /usr/local/freesurfer/average/mideface-atlas/samseg-options.json
uptime: Command not found.
upt: Subscript out of range.
ERROR:

**Comment by yhuang43** [comment]
uptime is a system command. Can you check if it is in your PATH? It is probably in /usr/bin.

**Comment by dngreve** [comment]
uptime is being run from fs_time. You can turn off this behavior with
unsetenv FS_TIME_ALLOW
But it will be good to know that uptime is not available on your platform.

On 12/22/2022 2:21 PM, yhuang43 wrote:
>
>         External Email - Use Caution
>
> uptime is a system command. Can you check if it is in your PATH? It is 
> probably in /usr/bin.
>
> —
> Reply to this email directly, view it on GitHub 
> <https://secure-web.cisco.com/19gAFbsZNx_rqyaVGKMI8XQs9E9HiZa4izB3uLzDblsBRyUwP7VSxs_b2rDT8i5mUfkufKkYHUhBcLDkmkXhYaSw-jpVs7VwVAnylELt8fl6JDMVlzm8v5tS73mcv1zuLrV2tJC1O6h6HeMCfr2xchCcSRI1_54fUf3LHlMQmZBeuQNMiPBsUsr9VIK0xp5K5dhj2H7_VC0AkyEAe66LXAN8G7KNGgHCS_5qVPZ5kymUktFi5BqxQr6cgNaVHrgvvKP49aceWaqZqTmNZG7F5pBQnTv7zEp-thHxz_FvVXsHM5lluXEwUzf34jDgs3r0R/https%3A%2F%2Fgithub.com%2Ffreesurfer%2Ffreesurfer%2Fissues%2F1042%23issuecomment-1363262517>, 
> or unsubscribe 
> <https://secure-web.cisco.com/1JkKCRH39RnUG8ImM_eqWqLJnQPIYrN4X7oSo8OfJEOvDBfvhgNikwOTxVwHZx__xYhG4qLr6ciWD8GMQIOsBDtPadn6oLJCb8KEWatr6jbBQY24jw3KCXCwCN7kOMu0kOxzC3WYJkvoTTa_Y-oVpUsVd3rXSmY_4FAi0Y52NKQxxXMiaaspMmJ0ugw3c8Krp0RojLA2P2agMV8Ua5D0m8qeM25NaLhxHbuQeqxuvcw-oZVKJQVuy-zkpqm8Q3WlkkKnb9-bNRGLXEqvI1b7DQLGY2lvjo90kHBDcg6egvcos4M5r4sz952kKkb4qUr05/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGIX2VSIVMJKLZCKUEFX573WOSS2DANCNFSM6AAAAAATEWYU4Y>.
> You are receiving this because you are subscribed to this 
> thread.Message ID: 
> ***@***.***>
>
The information in this e-mail is intended only for the person to whom it is addressed.  If you believe this e-mail was sent to you in error and the e-mail contains patient information, please contact the Mass General Brigham Compliance HelpLine at https://www.massgeneralbrigham.org/complianceline <https://www.massgeneralbrigham.org/complianceline> .
Please note that this e-mail is not secure (encrypted).  If you do not wish to continue communication over unencrypted e-mail, please notify the sender of this message immediately.  Continuing to send or respond to e-mail after receiving this message means you understand and accept this risk and wish to continue to communicate over unencrypted e-mail.

**Comment by klemens-egger** [comment]
I tried to find `uptime`, but it does not seem to be there. 

also tried to `unset FS_TIME_ALLOW` (using bash), but it did not solve the issue and the `mideface` gives the same error still.
Could it be that the docker image `docker pull freesurfer/freesurfer:7.3.2` is not downloading every dependency or do you have another idea?

**Comment by yhuang43** [comment]
use 'export FS_TIME_ALLOW=0'  for bash

**Comment by yhuang43** [comment]
You can also 'export FSTIME_LOAD=0' to just skip uptime. This is probably better because it will still report the execution time.

**Comment by klemens-egger** [comment]
Ah perfect, this did the trick. `mideface` could run now till the end. Thank you so much!
